"""
scripts/train_sft.py  —  SFT entry-point.

ALL configuration is imported from src/edge_cloud_llm/config.py.
To change any setting edit config.py — do NOT edit this file.
"""
from __future__ import annotations

import json
import math
from pathlib import Path

import torch
from torch.optim.lr_scheduler import LambdaLR

from edge_cloud_llm.config import MODEL, DATA, SFT, build_model
from edge_cloud_llm.data import (
    BPETokenizer,
    LengthCurriculumDataset,
    PackedSFTDataset,
    SFTCollator,
)
from edge_cloud_llm.data.sft_dataset import SFTBatch
from edge_cloud_llm.model import apply_lora_to_model, merge_lora_weights
from edge_cloud_llm.training import SFTTrainer


def load_sft_jsonl(path: str, tokenizer: BPETokenizer,
                   max_examples: int | None = None) -> list[dict]:
    records, skipped = [], 0
    with open(path, encoding="utf-8") as f:
        for line in f:
            if max_examples and len(records) >= max_examples:
                break
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                skipped += 1
                continue
            p = tokenizer.encode(row["prompt"],   add_special_tokens=False)
            r = tokenizer.encode(row["response"], add_special_tokens=False)
            if p and r:
                records.append({"prompt_ids": p, "response_ids": r})
            else:
                skipped += 1
    print(f"Loaded {len(records)} SFT examples  ({skipped} skipped)")
    return records


def build_lr_scheduler(optimizer, warmup_steps: int, total_steps: int):
    def lr_lambda(step: int) -> float:
        if step < warmup_steps:
            return step / max(1, warmup_steps)
        progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
        return max(0.1, 0.5 * (1.0 + math.cos(math.pi * progress)))
    return LambdaLR(optimizer, lr_lambda)


def main():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")
    print(f"Model : n_embd={MODEL.n_embd}, n_head={MODEL.n_head}, "
          f"n_layer={MODEL.n_layer}, block_size={MODEL.block_size}")
    print(f"SFT   : epochs={SFT.epochs}, batch={SFT.batch_size}, "
          f"lora={SFT.use_lora} (rank={SFT.lora_rank})")

    # ── Tokenizer ─────────────────────────────────────────────────────────────
    tokenizer = BPETokenizer.from_file(DATA.tokenizer_path)
    print(f"Vocab size: {tokenizer.vocab_size}")

    # ── Model  (built from the same ModelConfig as train_base.py) ─────────────
    # dropout=0.0 during SFT is standard practice
    model = build_model(tokenizer.vocab_size, dropout_override=0.0)

    if SFT.base_checkpoint and Path(SFT.base_checkpoint).exists():
        ckpt = torch.load(SFT.base_checkpoint, map_location="cpu")
        model.load_state_dict(ckpt["model_state_dict"])
        print(f"Loaded checkpoint: {SFT.base_checkpoint}")
    else:
        print("WARNING: no base checkpoint found — training from random init")

    # ── LoRA ──────────────────────────────────────────────────────────────────
    if SFT.use_lora:
        model = apply_lora_to_model(
            model,
            target_modules = SFT.lora_target_modules,
            rank           = SFT.lora_rank,
            lora_alpha     = SFT.lora_alpha,
            lora_dropout   = SFT.lora_dropout,
        )
        trainable_params = [p for p in model.parameters() if p.requires_grad]
    else:
        for p in model.parameters():
            p.requires_grad_(True)
        trainable_params = list(model.parameters())

    # ── Dataset ───────────────────────────────────────────────────────────────
    raw_data = load_sft_jsonl(DATA.sft_data_path, tokenizer,
                              max_examples=DATA.sft_max_examples)

    if SFT.use_context_packing:
        train_dataset = PackedSFTDataset(
            raw_data       = raw_data,
            context_length = MODEL.block_size,
            bos_token_id   = tokenizer.bos_token_id,
            eos_token_id   = tokenizer.eos_token_id,
            pad_token_id   = tokenizer.pad_token_id,
        )
        def pack_collate(batch):
            return SFTBatch(
                input_ids      = torch.stack([b["input_ids"]      for b in batch]),
                labels         = torch.stack([b["labels"]         for b in batch]),
                attention_mask = torch.stack([b["attention_mask"] for b in batch]),
            )
        collate_fn = pack_collate
    else:
        train_dataset = LengthCurriculumDataset(
            raw_data = raw_data,
            stages   = SFT.curriculum_stages,
        )
        collate_fn = SFTCollator(
            pad_token_id = tokenizer.pad_token_id,
            bos_token_id = tokenizer.bos_token_id,
            eos_token_id = tokenizer.eos_token_id,
            max_length   = MODEL.block_size,   # ← uses MODEL, not a separate SFT field
        )

    # ── Optimiser + scheduler ─────────────────────────────────────────────────
    optimizer = torch.optim.AdamW(
        trainable_params,
        lr=SFT.learning_rate,
        weight_decay=SFT.weight_decay,
    )
    steps_per_epoch = math.ceil(len(train_dataset) / max(1, SFT.batch_size)
                                / max(1, SFT.grad_accum_steps))
    total_steps = steps_per_epoch * SFT.epochs
    scheduler = build_lr_scheduler(optimizer, SFT.warmup_steps, max(1, total_steps))

    # ── Trainer ───────────────────────────────────────────────────────────────
    trainer = SFTTrainer(
        model            = model,
        optimizer        = optimizer,
        device           = device,
        sft_dataset      = train_dataset,
        collate_fn       = collate_fn,
        batch_size       = SFT.batch_size,
        val_loader       = None,
        output_dir       = SFT.output_dir,
        scheduler        = scheduler,
        grad_accum_steps = SFT.grad_accum_steps,
        use_amp          = SFT.use_amp,
        gradient_clip    = SFT.gradient_clip,
    )

    # ── Training loop ─────────────────────────────────────────────────────────
    best_loss = float("inf")
    print(f"\n{'='*55}\nStarting SFT  ({SFT.epochs} epochs)\n{'='*55}")

    for epoch in range(1, SFT.epochs + 1):
        print(f"\n── Epoch {epoch}/{SFT.epochs} ──")
        train_loss = trainer.train_epoch()
        print(f"  train_loss={train_loss:.4f}  "
              f"lr={optimizer.param_groups[0]['lr']:.2e}")

        trainer.log_metrics(epoch, train_loss, val_loss=0.0)
        trainer.save_checkpoint(f"sft_epoch_{epoch}.pt", epoch=epoch)

        if train_loss < best_loss:
            best_loss = train_loss
            trainer.save_checkpoint("sft_best.pt", epoch=epoch)
            print("  → best checkpoint saved")

        if not SFT.use_context_packing and isinstance(train_dataset, LengthCurriculumDataset):
            train_dataset.advance_stage()

    # ── Merge LoRA ────────────────────────────────────────────────────────────
    if SFT.use_lora and SFT.merge_weights_after_training:
        print("\nMerging LoRA weights…")
        merge_lora_weights(model)
        merged_path = Path(SFT.output_dir) / "sft_merged.pt"
        torch.save({"model_state_dict": model.state_dict()}, merged_path)
        print(f"Merged model → {merged_path}")

    print(f"\nSFT complete. Best loss: {best_loss:.4f}")


if __name__ == "__main__":
    main()
