"""
scripts/train_base.py  —  Pretraining entry-point.

ALL configuration is imported from src/edge_cloud_llm/config.py.
To change any setting (model size, epochs, batch size, data slice, …)
edit config.py — do NOT edit this file.
"""
from __future__ import annotations

import math
from pathlib import Path

import torch
from torch.optim.lr_scheduler import LambdaLR

from edge_cloud_llm.config import MODEL, DATA, BASE, build_model
from edge_cloud_llm.data import create_dataloaders
from edge_cloud_llm.training import Trainer


def build_lr_scheduler(optimizer, warmup_steps: int, total_steps: int):
    def lr_lambda(step: int) -> float:
        if step < warmup_steps:
            return step / max(1, warmup_steps)
        progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
        return max(0.1, 0.5 * (1.0 + math.cos(math.pi * progress)))
    return LambdaLR(optimizer, lr_lambda)


def main():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Device: {device}")
    print(f"Model : n_embd={MODEL.n_embd}, n_head={MODEL.n_head}, "
          f"n_layer={MODEL.n_layer}, block_size={MODEL.block_size}")
    print(f"Data  : train_chars={DATA.train_chars}, val_chars={DATA.val_chars}")
    print(f"Train : epochs={BASE.epochs}, batch={BASE.batch_size}, "
          f"accum={BASE.grad_accum_steps}, lr={BASE.learning_rate}")

    # ── Data ─────────────────────────────────────────────────────────────────
    train_loader, val_loader, tokenizer = create_dataloaders(
        tokenizer_path = DATA.tokenizer_path,
        block_size     = MODEL.block_size,
        batch_size     = BASE.batch_size,
        train_chars    = DATA.train_chars,
        val_chars      = DATA.val_chars,
    )
    print(f"Train batches: {len(train_loader)}  |  Val batches: {len(val_loader)}")
    print(f"Vocab size: {tokenizer.vocab_size}")

    # ── Model ─────────────────────────────────────────────────────────────────
    model = build_model(tokenizer.vocab_size)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"Parameters: {n_params:,}")

    # ── Optimiser + scheduler ─────────────────────────────────────────────────
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=BASE.learning_rate,
        weight_decay=BASE.weight_decay,
    )
    total_steps = (len(train_loader) * BASE.epochs) // max(1, BASE.grad_accum_steps)
    scheduler = build_lr_scheduler(optimizer, BASE.warmup_steps, max(1, total_steps))

    # ── Trainer ───────────────────────────────────────────────────────────────
    trainer = Trainer(
        model            = model,
        optimizer        = optimizer,
        device           = device,
        train_loader     = train_loader,
        val_loader       = val_loader,
        output_dir       = BASE.output_dir,
        scheduler        = scheduler,
        grad_accum_steps = BASE.grad_accum_steps,
        use_amp          = BASE.use_amp,
    )

    start_epoch = 1
    if BASE.resume_from and Path(BASE.resume_from).exists():
        last_epoch = trainer.load_checkpoint(BASE.resume_from)
        start_epoch = last_epoch + 1
        print(f"Resumed from {BASE.resume_from}, starting at epoch {start_epoch}")

    # ── Training loop ─────────────────────────────────────────────────────────
    # best_val_loss = float("inf")

    # for epoch in range(start_epoch, BASE.epochs + 1):
    #     print(f"\n── Epoch {epoch}/{BASE.epochs} ──")
    #     train_loss = trainer.train_epoch()
    #     val_loss   = trainer.evaluate(max_batches=BASE.eval_batches)

    #     trainer.log_metrics(epoch, train_loss, val_loss)
    #     trainer.save_checkpoint(f"epoch_{epoch}.pt", epoch=epoch)

    #     print(f"  train={train_loss:.4f}  val={val_loss:.4f}  "
    #           f"lr={optimizer.param_groups[0]['lr']:.2e}")

    #     if val_loss < best_val_loss:
    #         best_val_loss = val_loss
    #         trainer.save_checkpoint("best.pt", epoch=epoch)
    #         print("  → best checkpoint saved")

    # in the training loop, replace the existing loop with this:
    best_val_loss = float("inf")
    patience      = 2        # stop if val loss doesn't improve for 2 epochs in a row
    no_improve    = 0

    for epoch in range(start_epoch, BASE.epochs + 1):
        print(f"\n── Epoch {epoch}/{BASE.epochs} ──")
        train_loss = trainer.train_epoch()
        val_loss   = trainer.evaluate(max_batches=BASE.eval_batches)

        trainer.log_metrics(epoch, train_loss, val_loss)
        trainer.save_checkpoint(f"epoch_{epoch}.pt", epoch=epoch)

        gap = val_loss - train_loss
        print(f"  train={train_loss:.4f}  val={val_loss:.4f}  "
            f"gap={gap:.4f}  lr={optimizer.param_groups[0]['lr']:.2e}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            no_improve    = 0
            trainer.save_checkpoint("best.pt", epoch=epoch)
            print("  → best checkpoint saved")
        else:
            no_improve += 1
            print(f"  → no improvement ({no_improve}/{patience})")
            if no_improve >= patience:
                print(f"  → early stopping at epoch {epoch}")
                break

    print(f"\nDone. Best val loss: {best_val_loss:.4f}")
    print(f"Log: {BASE.output_dir}/training_log.csv")


if __name__ == "__main__":
    main()
